from __future__ import annotations

from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse

from app.core.config import settings, PROJECT_ROOT
from app.core.database import initialize_database
from app.routers import chat, downloads, hardware, inference, logs, models, settings as settings_router
from app.services.logging_service import log
from app.services.registry import scan_models


@asynccontextmanager
async def lifespan(app: FastAPI):
    initialize_database()
    try:
        scan_models()
    except Exception as exc:
        log("ERROR", "startup", "Initial model scan failed", {"error": str(exc)})
    log("INFO", "startup", "Backend started")
    yield
    log("INFO", "startup", "Backend stopped")


app = FastAPI(title=settings.app_name, version="0.1.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=list(settings.allowed_origins),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


app.include_router(chat.router, prefix="/api")
app.include_router(downloads.router, prefix="/api")
app.include_router(hardware.router, prefix="/api")
app.include_router(inference.router, prefix="/api")
app.include_router(logs.router, prefix="/api")
app.include_router(models.router, prefix="/api")
app.include_router(settings_router.router, prefix="/api")


# Catch-all router to serve Next.js statically compiled files
frontend_dir = PROJECT_ROOT / "frontend" / "out"


@app.get("/{path:path}")
async def serve_frontend(request: Request, path: str):
    if path.startswith("api/"):
        return HTMLResponse("API endpoint not found", status_code=404)

    file_path = frontend_dir / path
    if file_path.is_file():
        return FileResponse(file_path)

    if not path:
        index_path = frontend_dir / "index.html"
        if index_path.is_file():
            return FileResponse(index_path)

    # Support clean URLs generated by Next.js static exports (e.g. /chats -> /chats.html)
    html_path = frontend_dir / f"{path}.html"
    if html_path.is_file():
        return FileResponse(html_path)

    dir_index_path = frontend_dir / path / "index.html"
    if dir_index_path.is_file():
        return FileResponse(dir_index_path)

    # Fallback to SPA root index for dynamic React routing elements
    fallback_path = frontend_dir / "index.html"
    if fallback_path.is_file():
        return FileResponse(fallback_path)

    return HTMLResponse(
        "Frontend static assets not built. Run <code>npm run build</code> inside the <code>frontend</code> folder first.",
        status_code=404
    )


